# Generated by Django 4.0.2 on 2022-04-28 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0006_alter_ovchivmanagement_substitution_firstline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 20, 14, 47, 108486)),
        ),
        migrations.AlterField(
            model_name='sinovuyuteenprandpostassesment',
            name='date_assment',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
