# Generated by Django 4.0.2 on 2022-04-28 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0007_alter_ovchivmanagement_substitution_firstline_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinovuyuteenprandpostassesment',
            name='date_assment',
        ),
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 20, 15, 45, 786126)),
        ),
    ]
