# Generated by Django 4.0.2 on 2022-04-29 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0008_remove_sinovuyuteenprandpostassesment_date_assment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SinovuyuTeenPrAndPostAssesment',
            new_name='SinovuyuTeenPreAndPostAssesment',
        ),
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 15, 23, 32, 469327)),
        ),
    ]
