# Generated by Django 4.0.2 on 2022-04-29 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_registry', '0001_initial'),
        ('cpovc_forms', '0009_rename_sinovuyuteenprandpostassesment_sinovuyuteenpreandpostassesment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovchivmanagement',
            name='substitution_firstline_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 15, 48, 37, 472086)),
        ),
        migrations.CreateModel(
            name='OVCPrevSinovyoTeenEvaluation',
            fields=[
                ('evaluation_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('bd_age', models.CharField(max_length=10)),
                ('bd_sex', models.CharField(max_length=10)),
                ('bd_read', models.CharField(max_length=10)),
                ('bd_education_level', models.CharField(max_length=10)),
                ('bd_class', models.CharField(max_length=10)),
                ('bd_bd_boarding_status', models.CharField(max_length=10)),
                ('bd_biological_children', models.CharField(max_length=10)),
                ('bd_live_biological_fatherbd_live_bilogical_mother', models.CharField(max_length=10)),
                ('bd_disability', models.CharField(max_length=10)),
                ('bd_money_essentials', models.CharField(max_length=10)),
                ('bd_violence', models.CharField(max_length=10)),
                ('bd_adult_unwell', models.CharField(max_length=10)),
                ('bd_child_unwell', models.CharField(max_length=10)),
                ('bd_miss_school', models.CharField(max_length=10)),
                ('bd_hiv_status', models.CharField(max_length=10)),
                ('bd_hiv_prevention', models.CharField(max_length=10)),
                ('bd_two_meals', models.CharField(max_length=10)),
                ('bd_missing_meal', models.CharField(max_length=10)),
                ('rc_discuss_child_needs', models.CharField(max_length=10)),
                ('rc_discipline', models.CharField(max_length=10)),
                ('rc_tells_bothering', models.CharField(max_length=10)),
                ('rc_involve_decisions', models.CharField(max_length=10)),
                ('cb_child_obedient', models.CharField(max_length=10)),
                ('cb_figths_children', models.CharField(max_length=10)),
                ('dc_often_discipline', models.CharField(max_length=10)),
                ('dc_physical_discipline', models.CharField(max_length=10)),
                ('dc_upset_child', models.CharField(max_length=10)),
                ('sp_physical_punish', models.CharField(max_length=10)),
                ('fs_unhappy', models.CharField(max_length=10)),
                ('fs_too_tired', models.CharField(max_length=10)),
                ('fs_hopeful', models.CharField(max_length=10)),
                ('fmp_pre_grouping_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('timestamp_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('sync_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpovc_registry.regperson')),
                ('ref_caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preval_caregiver', to='cpovc_registry.regperson')),
            ],
            options={
                'db_table': 'ovc_prev_sinovuyo_teen_evaluation',
            },
        ),
    ]
